Feature/seller product
ptt-project/ptt-front pull request #25
Opened 2022-08-05 12:49 UTC by parinpond

แก้ไขi18n

2022-08-06 09:39 UTC, einost commented on modules/SellerMyProducts/components/List/index.tsx
>    const columns: ColumnsType<IDataType> = [
ไม่ประกาศแบบนี้แล้วเพราะไม่ error hook rule แล้ว

2022-08-06 09:40 UTC, einost commented on modules/SellerMyProducts/components/SellerMyProductsForm/components/Sales.tsx
ไม่ประกาศแบบนี้แล้วเพราะไม่ error hook rule แล้ว

2022-08-06 09:42 UTC, einost commented on modules/SellerPoint/components/SellerPointTabs/index.tsx
function ควรอยู่ภายใต้ component

2022-08-06 09:44 UTC, einost commented on pages/seller/settings/product/add-list.tsx
> +}
ฝากเช็คอีกทีถ้าหน้าไหนจะต้อง fetch data จาก api มา displayให้ใช้ getServerSideProps ถ้าหน้าไหนไม่มีให้ใช้ getStaticProps

2022-08-06 09:44 UTC, einost commented on pages/seller/settings/product/list.tsx
> +const SellerMyProductsPage: FC = () => <SellerMyProducts />
ฝากเช็คอีกทีถ้าหน้าไหนจะต้อง fetch data จาก api มา displayให้ใช้ getServerSideProps ถ้าหน้าไหนไม่มีให้ใช้ getStaticProps

2022-08-06 09:44 UTC, einost commented on pages/seller/settings/shop/point.tsx
> +}
ฝากเช็คอีกทีถ้าหน้าไหนจะต้อง fetch data จาก api มา displayให้ใช้ getServerSideProps ถ้าหน้าไหนไม่มีให้ใช้ getStaticProps

2022-08-06 09:44 UTC, einost commented on pages/settings/account/info/add-phone.tsx
> +}
ฝากเช็คอีกทีถ้าหน้าไหนจะต้อง fetch data จาก api มา displayให้ใช้ getServerSideProps ถ้าหน้าไหนไม่มีให้ใช้ getStaticProps

2022-08-06 09:44 UTC, einost commented on pages/settings/account/info/email.tsx
> +}
ฝากเช็คอีกทีถ้าหน้าไหนจะต้อง fetch data จาก api มา displayให้ใช้ getServerSideProps ถ้าหน้าไหนไม่มีให้ใช้ getStaticProps

2022-08-06 09:44 UTC, einost commented on pages/settings/account/info/index.tsx
> +}
ฝากเช็คอีกทีถ้าหน้าไหนจะต้อง fetch data จาก api มา displayให้ใช้ getServerSideProps ถ้าหน้าไหนไม่มีให้ใช้ getStaticProps

2022-08-06 09:44 UTC, einost commented on pages/settings/account/info/phone.tsx
>  const PhonePage: FC = () => <Phone />
ฝากเช็คอีกทีถ้าหน้าไหนจะต้อง fetch data จาก api มา displayให้ใช้ getServerSideProps ถ้าหน้าไหนไม่มีให้ใช้ getStaticProps

2022-08-06 09:45 UTC, einost requested changes
ฝากเช็คใน comment ด้วยครับ

2022-08-07 05:19 UTC, parinpond commented on modules/SellerMyProducts/components/List/index.tsx
>    const columns: ColumnsType<IDataType> = [
แก้ไขแล้วค่ะ

2022-08-07 05:20 UTC, parinpond commented on modules/SellerMyProducts/components/SellerMyProductsForm/components/Sales.tsx
แก้ไขแล้วค่ะ

2022-08-07 05:46 UTC, parinpond commented
แก้ไขเสร็จแล้วค่ะ รบกวนตรวจสอบอีกที

2022-08-07 10:09 UTC, einost commented on modules/SellerPoint/components/Review/index.tsx
>                }
ใช้ : ขั้นระหว่าง namepsace

2022-08-07 10:10 UTC, einost requested changes
เหลืออีกนิดนึงครับ

2022-08-07 12:03 UTC, parinpond commented
เรียบร้อยค่ะ

2022-08-07 12:15 UTC, einost approved these changes

2022-08-07 12:15 UTC, merged