Feature/account info
ptt-project/ptt-front pull request #30
Opened 2022-08-17 14:02 UTC by parinpond

2022-08-18 10:11 UTC, einost commented on .vscode/settings.json
>    "i18n-ally.pathMatcher": "{locale}/{namespaces}.json",
formatter หน้านี้ทีครับ

2022-08-18 10:12 UTC, einost commented on constants/endpoint.const.ts
>    },
เปลี่ยน MOBILE เป็น MOBILES

2022-08-18 10:14 UTC, einost commented on interfaces/member.interface.ts
> +export interface IEmailUpdate {
IMemberEmailUpdate

2022-08-18 10:14 UTC, einost commented on interfaces/member.interface.ts
> +  mobile: string
IMemberMobile

2022-08-18 10:16 UTC, einost commented on modules/Profile/components/Email/index.tsx
> +interface IProps {
IEmailProps

2022-08-18 10:17 UTC, einost commented on modules/Profile/index.tsx
> +                      name="firstname"
ถาม backend อีกทีว่าไม่ได้ใช้ camel case หรอ

2022-08-18 10:19 UTC, einost requested changes
มี comment ครับ อย่าลืมดู impact หน้าอื่นๆนะ

2022-08-18 13:43 UTC, parinpond commented
แก้ไขเรียบร้อยแล้วค่ะ

2022-08-19 11:00 UTC, einost approved these changes

2022-08-19 11:01 UTC, merged